# 외부에서 80번 포트로 오면
server {
    listen 80;

    location / {
        # → Spring Boot 8080번으로 전달
        proxy_pass http://app:8080;

        # 실제 사용자 IP를 Spring Boot에 알려줌
        proxy_set_header X-Real-IP $remote_addr;
    }
}
